### ISSUE TITLE
Fingerprint authentication is a must have feature...

### ISSUE THREAD

**Issue by Bantul-the-great** [keshav-space/safenotes#57]
1. Problem: I'm always frustrated while putting the passphrase every time at login...
2. Solution: Having the basic concept of encryption I hope there are secure ways to integrate fingerprint authentication with the app eliminating the need of putting passphrase every time which is a must have feature in such a polished and perfect note-taking app.... It should not be considered just a feature, but rather a necessity for mobile devices... Password managers like KeepassDX and Bitwarden and so on, being so critical in security perspective, offers fingerprint auth.. Why not this amazing note taking app?
3. Extra: I really like the line saying "with great security comes the great responsibility of remembering the passphrase".. But I believe that the ease of logging in with biometric auth should be made available.... Rest is the users' decision....
4. You do your best... Users will see the rest😇...And thanks man for offering the community with such a beautiful, secure, and offline alternative..

**Comment by keshav-space** [comment]
@Bantul-the-great  I see that it could be pretty cumbersome at times. But let me assure you that it was a well-thought-out decision.

- We not only need the passphrase to authenticate user, but the same is used to decrypt notes because your passphrase is never stored in the memory which is the best decision from a security standpoint.

- Biometrics is a robust way of identity pinning but it is not that great for authentication and it's for this same reason whenever you boot your device you are asked to enter password/pin/pattern before activating biometric authentication.

> Let me explain this to you by analogy suppose you are traveling with a briefcase filled with gold and the briefcase is fitted with the best of the best lock, but the key is always hanging through your bracelet. You see that is not good because you could be sleeping/unconscious and someone can snoop on your gold. In this story briefcase is your notes and the key is your fingerprints, but the situation is worse because not only your key is guaranteed to be in your hand but you are leaving the blueprint of your key everywhere you go, and worst you can not change your fingerprint if it gets compromised. Surely not everyone around will have the technical capability to clone your biometric identity but if you're storing state secrets you don’t want to take any chance.

Having addressed the reason for the same now let's address the second part of your suggestion i.e. providing an option to enable fingerprint authentication and let the user decide according to their threat perception.
- This could be done but that won't be the default behavior and user would need to enable that explicitly from the settings. Moreover, users will be warned about the security implication mentioned above.

**Comment by Loki-101** [comment]
Pattern unlock would be a great option too.

**Comment by landry314** [comment]
what if an attacker forces your finger onto the phone? that isn't hard to do. harder to get something out of your brain. i never understood why people would trust fingerprint authentication without ALSO a password.

**Comment by Loki-101** [comment]
Simple. Make fingerprint authentication optional and turned off by default.

**Comment by Zzziius** [comment]
I have some suggestions, thoughts, ideas if you decide to implement optional biometrics authentication. Sooo hear me out... 
 
-When an user enables the feature. They then will have to enroll new sets of bio credentials rather than using the system wide set. So then everything will be handled & saved in-app. I say this because more than one person can register their prints in the system. (I have 1 on my child's) Which usually grants access to anything logined in by the user on that device the feature is enabled for.  Say you're okay w/ that w/ a partner but you'd rather your notes stay private. Enrolling in-app at bio set up will fix that. 

-The login & passphrase screen should stay the same w/o it prompting for fingerprint. If you enabled that feature you know, so you don't need to be prompted on it & no one else needs to know there's another way into it other than a passphrase. 

-Maybe once you auth w/ fingerprint you just have to select an image or something of the sort (you previously chose as your secure image during bio enrollment) or select image w/ username then authenticate w/ fingerprint. 

Idk if any or some of that is possible, secure, nor realistic. It just came to mind so I was curious.
